// GENERATED by `pnpm diagram` from the src/framework/*.json files — do not edit by hand.
// The installed framework vocabularies (core first): edge tags + overlay metadata vocabularies.
export const FRAMEWORKS = [
  {
    "framework": "philomatic-core",
    "version": 1,
    "description": "Philomatic's built-in vocabulary — the tags that carry meaning on generic edges (LINK / ABOUT / INCLUDES) and the overlay metadata vocabularies. The engine never interprets these; UIs render them and (F1, later) validation rules report over them.",
    "edgeTags": [
      {
        "name": "Explains",
        "on": {
          "type": "ABOUT",
          "srcKind": "source",
          "dstKind": "concept"
        },
        "direction": "directed",
        "inverseLabel": "explained by",
        "publish": true,
        "description": "covers the theory — a candidate pool, never auto-pulled into a track"
      },
      {
        "name": "Demonstrates",
        "on": {
          "type": "ABOUT",
          "srcKind": "source",
          "dstKind": "concept"
        },
        "direction": "directed",
        "publish": true,
        "description": "shows the concept applied in practice"
      },
      {
        "name": "Exercises",
        "on": {
          "type": "ABOUT",
          "srcKind": "source",
          "dstKind": "concept"
        },
        "direction": "directed",
        "publish": true,
        "description": "interactive — tests the concept hands-on"
      },
      {
        "name": "Seminal",
        "on": {
          "type": "INCLUDES",
          "srcKind": "track",
          "dstKind": "source"
        },
        "direction": "directed",
        "publish": true,
        "description": "the cornerstone source of this track"
      },
      {
        "name": "Foundational",
        "on": {
          "type": "INCLUDES",
          "srcKind": "track",
          "dstKind": "concept"
        },
        "direction": "directed",
        "publish": true,
        "description": "a concept this track is built around"
      },
      {
        "name": "Refines",
        "on": {
          "type": "LINK",
          "srcKind": "question",
          "dstKind": "question"
        },
        "direction": "directed",
        "inverseLabel": "refined by",
        "publish": true,
        "description": "sharpens a broader question"
      },
      {
        "name": "Complements",
        "on": {
          "type": "LINK",
          "srcKind": "track",
          "dstKind": "track"
        },
        "direction": "symmetric",
        "publish": true,
        "description": "these two tracks go well together"
      },
      {
        "name": "AnalogousTo",
        "on": {
          "type": "LINK",
          "srcKind": "concept",
          "dstKind": "concept"
        },
        "direction": "symmetric",
        "publish": true,
        "description": "these two concepts rhyme — understanding one helps with the other"
      },
      {
        "name": "IsEvidenceFor",
        "on": {
          "type": "LINK",
          "srcKind": "concept",
          "dstKind": "concept"
        },
        "direction": "directed",
        "publish": true,
        "polarity": "for",
        "description": "supports or substantiates that concept"
      },
      {
        "name": "SubfieldOf",
        "on": {
          "type": "LINK",
          "srcKind": "concept",
          "dstKind": "concept"
        },
        "direction": "directed",
        "inverseLabel": "superfield of",
        "hierarchy": "taxonomy",
        "hierarchyRole": "parent",
        "publish": true,
        "description": "this field of study specializes that one (ML #SubfieldOf CS) — taxonomy, NOT learning order: a subfield is not a prerequisite (PREREQUISITE_OF stays the sequencing primitive). Fields ARE concepts when they are things you learn about; classifying OTHER entities into a field stays a #domain:* tag"
      },
      {
        "name": "TopicOf",
        "on": {
          "type": "LINK",
          "srcKind": "concept",
          "dstKind": "concept"
        },
        "direction": "directed",
        "inverseLabel": "parent topic of",
        "hierarchy": "taxonomy",
        "hierarchyRole": "attachment",
        "publish": true,
        "description": "this concept is subject matter WITHIN that field (Normality #TopicOf Descriptive Statistics) — the middle rung of the taxonomy: #SubfieldOf is field-inside-field, #TopicOf is topic-inside-field, and classifying non-concept entities into a field stays a #domain:* tag. Not learning order (PREREQUISITE_OF) and not containment of meaning — a topic can belong to several fields"
      },
      {
        "name": "DrawsOn",
        "on": {
          "type": "LINK",
          "srcKind": "concept",
          "dstKind": "concept"
        },
        "direction": "directed",
        "inverseLabel": "informs",
        "publish": true,
        "description": "this field borrows methods or results from that one (Cognitive Science #DrawsOn Linguistics) — interdisciplinary influence, weaker than #SubfieldOf and looser than #IsEvidenceFor"
      },
      {
        "name": "RefersTo",
        "on": {
          "type": "LINK",
          "srcKind": "source",
          "dstKind": "source"
        },
        "direction": "directed",
        "inverseLabel": "referenced by",
        "publish": true,
        "description": "keep that source at hand while working through this one"
      },
      {
        "name": "Expands",
        "on": {
          "type": "LINK",
          "srcKind": "source",
          "dstKind": "source"
        },
        "direction": "directed",
        "publish": true,
        "description": "goes deeper than that one"
      },
      {
        "name": "DerivativeOf",
        "on": {
          "type": "LINK",
          "srcKind": "source",
          "dstKind": "source"
        },
        "direction": "directed",
        "publish": true,
        "description": "based on that one — a summary, translation, or adaptation"
      }
    ],
    "entityTags": [
      {
        "name": "difficulty",
        "degree": true,
        "description": "How demanding this is, 1-5. NOT published (owner, 2026-08-03): difficulty is relative to the reader, so one learner's 3 is another's 1 — publishing it states a fact about the work that is really a fact about the person. Note it was never engine-recognised before 2026-08-03 despite being the canonical degree-tag EXAMPLE in four source comments. A framework of one's own may declare it publishable — core's judgement binds core, not every framework."
      },
      {
        "name": "NeedsSources",
        "on": [
          "concept"
        ],
        "publish": true,
        "description": "A published REQUEST FOR HELP: this concept is a declared gap. It must travel with the bundle because the unified track/contributions page (B-D12) renders from the PUBLISHED state — and a registry hosting that page has no live engine to ask. Considered for stripping 2026-08-03 as a private judgement; that reasoning was wrong, because the flag is the mechanism by which contributions are invited, not an opinion about one's own work."
      }
    ],
    "metadataFields": [
      {
        "name": "sentiment",
        "on": {
          "type": "ANNOTATES"
        },
        "vocabulary": [
          {
            "token": "aha",
            "label": "aha"
          },
          {
            "token": "pondering",
            "label": "pondering"
          },
          {
            "token": "confused",
            "label": "confused"
          }
        ]
      }
    ]
  },
  {
    "framework": "argument-diagramming",
    "version": 1,
    "description": "Argument structure over passages — the first non-core framework, proving the lens model: snippet↔snippet LINKs tagged with argumentative roles. Corpus-internal argument structure is framework vocabulary (a community's lens), distinct from the engine's polarity primitive (CLARIFIES/CONTRADICTS, which anchor passages to the ontology). LINKED (conjoint) premises use the tag grammar's subtype as a bundle key: #Supports:a edges into the same conclusion are jointly sufficient — neither premise supports alone — while bare #Supports is an independent (convergent) line. Bundles bind to the conclusion through the edges themselves, so a premise can join several arguments without ambiguity; reading a diagram back is a pure fold (group by conclusion + subtype). If argument mapping ever needs reified inference nodes, the promotion path is the deferred Claim/Answer nodes (ROADMAP §2.3). Bundle keys are OPAQUE AND TOOL-MINTED (the id doctrine: humans never hand-derive keys; capture surfaces mint short hashes — mnemonic keys in hand-authored payloads are a conscious choice). No registry, no uniqueness enforcement — collisions are structurally confined to one conclusion's inbound set, and the residue is F1 lint territory: singleton bundles (dangling conjunction / typo'd key), mixed bare+subtyped support on one edge, late/cross-asserter bundle joins.",
    "edgeTags": [
      {
        "name": "Supports",
        "on": {
          "type": "LINK",
          "srcKind": "snippet",
          "dstKind": "snippet"
        },
        "direction": "directed",
        "inverseLabel": "supported by",
        "subtypeRole": "bundle",
        "publish": true,
        "polarity": "for",
        "description": "this passage gives evidence or argument FOR that one; a subtype names a conjoint bundle (#Supports:a — jointly sufficient with the bundle's other premises), bare = independent"
      },
      {
        "name": "Opposes",
        "on": {
          "type": "LINK",
          "srcKind": "snippet",
          "dstKind": "snippet"
        },
        "direction": "directed",
        "inverseLabel": "opposed by",
        "subtypeRole": "bundle",
        "publish": true,
        "polarity": "against",
        "description": "this passage argues AGAINST that one — passage-level disagreement, kept, not resolved; subtypes bundle conjoint objections like #Supports"
      }
    ],
    "entityTags": [],
    "metadataFields": []
  },
  {
    "framework": "propositional-logic",
    "version": 1,
    "description": "Propositional structure over passages — the formal cousin of argument-diagramming: where #Supports says 'this passage gives reason to believe that one', these tags assert logical form. Snippets play propositions; connectives ride tags on snippet↔snippet LINKs. Conjunction reuses the bundle convention (#Implies:a — jointly-sufficient antecedents, same grammar as #Supports:a). Disjunctive antecedents need NO hyperedge: (A ∨ B) → C is exactly {A #Implies C, B #Implies C} — case analysis is two edges, so the one connective that looks like it demands arity 3 decomposes for free. Negation between passages is #Negates (the engine primitive CONTRADICTS anchors a passage to a CONCEPT; passage↔passage contradiction is framework vocabulary). Nothing here EVALUATES: well-formedness lint (a #Negates edge inside an #Implies:a bundle, circular implication chains) is F1 territory; truth-functional checking would be an enrich-side adapter, never an engine feature.",
    "edgeTags": [
      {
        "name": "Implies",
        "on": {
          "type": "LINK",
          "srcKind": "snippet",
          "dstKind": "snippet"
        },
        "direction": "directed",
        "inverseLabel": "implied by",
        "subtypeRole": "bundle",
        "publish": true,
        "description": "if this passage's claim holds, that one follows; a subtype names conjoint antecedents (#Implies:a — jointly sufficient, none implies alone), bare = sufficient on its own. (A ∨ B) → C is two bare edges: case analysis"
      },
      {
        "name": "EquivalentTo",
        "on": {
          "type": "LINK",
          "srcKind": "snippet",
          "dstKind": "snippet"
        },
        "direction": "symmetric",
        "publish": true,
        "description": "these passages assert logically equivalent claims — each implies the other (the biconditional)"
      },
      {
        "name": "Negates",
        "on": {
          "type": "LINK",
          "srcKind": "snippet",
          "dstKind": "snippet"
        },
        "direction": "symmetric",
        "publish": true,
        "description": "these passages assert contradictory claims — at most one can hold. Passage-level ¬; distinct from the engine's CONTRADICTS (passage vs concept) and from #Opposes (argues against, weaker than logical contradiction)"
      }
    ],
    "entityTags": [],
    "metadataFields": []
  },
  {
    "framework": "hermeneutics",
    "version": 1,
    "description": "Interpretive structure over texts — for readers of the Classics, scripture, law, or any corpus where the work is deciding what a passage MEANS. Passages (snippets) carry readings: a commentary passage #Interprets a primary passage; rival readings each #Interprets the same target and argue among themselves with argument-diagramming's #Supports/#Opposes (frameworks compose — a reading is just a passage, so the whole argument toolkit applies to interpretive disputes). #Tension keeps an apparent conflict between passages ON the record without resolving it — resolution, if any, is a reading that #Interprets each side. Work-level relations (a commentary on a work, a translation of a work) ride source↔source LINKs. The fourfold sense (quadriga) is a LEARNER-overlay metadata vocabulary on ANNOTATES — which sense a reading operates in is your judgment about your reading, not a fact about the text (D8: overlay edges only).",
    "edgeTags": [
      {
        "name": "Interprets",
        "on": {
          "type": "LINK",
          "srcKind": "snippet",
          "dstKind": "snippet"
        },
        "direction": "directed",
        "inverseLabel": "interpreted by",
        "publish": true,
        "description": "this passage offers a reading of that one — what it takes the target to mean. Rival readings each carry their own #Interprets edge; their dispute is #Supports/#Opposes between the readings"
      },
      {
        "name": "ParallelPassage",
        "on": {
          "type": "LINK",
          "srcKind": "snippet",
          "dstKind": "snippet"
        },
        "direction": "symmetric",
        "publish": true,
        "description": "these passages tell the same episode or teaching in different places — synoptic parallels, doublets, recensions"
      },
      {
        "name": "Alludes",
        "on": {
          "type": "LINK",
          "srcKind": "snippet",
          "dstKind": "snippet"
        },
        "direction": "directed",
        "inverseLabel": "alluded to by",
        "publish": true,
        "description": "this passage echoes or evokes that one — intertextual reference the author expects the reader to hear"
      },
      {
        "name": "Tension",
        "on": {
          "type": "LINK",
          "srcKind": "snippet",
          "dstKind": "snippet"
        },
        "direction": "symmetric",
        "publish": true,
        "description": "these passages appear to conflict — kept on the record, not resolved; a harmonizing reading #Interprets each side"
      },
      {
        "name": "CommentaryOn",
        "on": {
          "type": "LINK",
          "srcKind": "source",
          "dstKind": "source"
        },
        "direction": "directed",
        "inverseLabel": "commented on by",
        "publish": true,
        "description": "this work is a sustained commentary on that one"
      },
      {
        "name": "TranslationOf",
        "on": {
          "type": "LINK",
          "srcKind": "source",
          "dstKind": "source"
        },
        "direction": "directed",
        "inverseLabel": "translated as",
        "publish": true,
        "description": "this work renders that one in another language — sharper than core's #DerivativeOf when the tradition of translation is itself the object of study"
      }
    ],
    "entityTags": [],
    "metadataFields": [
      {
        "name": "sense",
        "on": {
          "type": "ANNOTATES"
        },
        "vocabulary": [
          {
            "token": "literal",
            "label": "literal / historical"
          },
          {
            "token": "allegorical",
            "label": "allegorical"
          },
          {
            "token": "tropological",
            "label": "tropological / moral"
          },
          {
            "token": "anagogical",
            "label": "anagogical"
          }
        ]
      }
    ]
  }
] as const;
