/**
 * pnpm diagram — render the edge taxonomy (alpha UI plan §2.6). Generated, never drawn:
 *   1. the Mermaid diagram between the markers in DATA_MODEL.md (GitHub renders it);
 *   2. `ui/src/generated/model.ts` — the glossary data the Model tab renders (the UI stays a
 *      transport-level client; baked data, not an engine import);
 *   3. the framework vocabulary (F0) baked for BOTH UIs — `ui/src/generated/framework.ts` and
 *      `src/extension/framework.gen.ts` (the popup may not import src/ past the lock line, so
 *      it gets its own baked copy; one source of truth: src/framework/philomatic-core.json).
 * test/diagram.test.ts asserts the artifacts match a regeneration — drift is a CI failure.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { FRAMEWORKS, taxonomy, taxonomyMermaid } from '../src/engine';

const r = (p: string): string => fileURLToPath(new URL(p, import.meta.url));

export const BEGIN = '<!-- edge-taxonomy:begin — generated by `pnpm diagram`; do not edit by hand -->';
export const END = '<!-- edge-taxonomy:end -->';

const dmPath = r('../DATA_MODEL.md');
const dm = readFileSync(dmPath, 'utf8');
if (!dm.includes(BEGIN) || !dm.includes(END)) {
  throw new Error('DATA_MODEL.md is missing the edge-taxonomy markers');
}
const block = `${BEGIN}\n\`\`\`mermaid\n${taxonomyMermaid()}\`\`\`\n${END}`;
writeFileSync(dmPath, dm.slice(0, dm.indexOf(BEGIN)) + block + dm.slice(dm.indexOf(END) + END.length));

const t = taxonomy();
const module = `// GENERATED by \`pnpm diagram\` from the engine's ENDPOINT_RULES — do not edit by hand.
// The UI stays a transport-level client: this file is baked data, not an engine import.
export const MODEL = ${JSON.stringify({ mermaid: taxonomyMermaid(), edges: t.edges, verbs: t.verbs }, null, 2)} as const;
`;
mkdirSync(r('../ui/src/generated'), { recursive: true });
writeFileSync(r('../ui/src/generated/model.ts'), module);

const frameworkModule = `// GENERATED by \`pnpm diagram\` from the src/framework/*.json files — do not edit by hand.
// The installed framework vocabularies (core first): edge tags + overlay metadata vocabularies.
export const FRAMEWORKS = ${JSON.stringify(FRAMEWORKS, null, 2)} as const;
`;
writeFileSync(r('../ui/src/generated/framework.ts'), frameworkModule);
writeFileSync(r('../src/extension/framework.gen.ts'), frameworkModule);

console.log('wrote the DATA_MODEL.md taxonomy block, ui/src/generated/{model,framework}.ts, and src/extension/framework.gen.ts');
